---
- hosts: localhost
  tasks:
    - name: Check for and install updates
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install fonts
      become: yes
      pacman:
        name: "{{ font_packages }}"
      vars:
        font_packages:
          - ttf-hack
          - adobo-source-code-pro-fonts
          - noto-fonts

    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles_repo }}"
        dest: ~/dotfiles/
        clone: yes
      vars:
        dotfiles_repo: https://github.com/tuxxy/dotfiles

    - name: Install .bashrc from dotfiles
      shell: 'mv ~/dotfiles/.bashrc ~/.'

    - name: Install and configure i3 w/ related packages
      block:
        - name: Install i3
          become: yes
          pacman:
            name: i3-wm,i3status,picom,feh

        - name: Install rofi from the AUR
          aur:
            name: rofi
            use: yay

        - name: Configure rofi
          shell: 'mv ~/dotfiles/rofi ~/.config/'

        - name: Configure .xinitrc
          shell: 'echo exec i3 > ~/.xinitrc'

        - name: Install i3 config from dotfiles
          shell: 'mv ~/dotfiles/i3 ~/.config/'

    - name: Install and configure firejail
      block:
        - name: Install firejail
          become: yes
          pacman:
            name: firejail

        - name: Configure firejail
          shell: 'mv ~/dotfiles/firejail ~/.config/'

    - name: Install and configure vim
      block:
        - name: Install .vimrc from dotfiles
          shell: 'mv ~/dotfiles/.vimrc ~/.'

        - name: Install plug.vim
          shell: 'curl -fLo ~/.vim/autoload/plug.vim --create-dirs "{{plug_url}}"'
          vars:
            plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

        - name: Install vim solarized
          shell: 'curl -fLo ~/.vim/colors/solarized.vim --create-dirs "{{solarized_url}}"'
          vars:
            solarized_url: https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim

        - name: Install vim plugins
          shell: "vim +'PlugInstall --sync' +qa"

    - name: Build and install st
      block:
        - name: Clone st
          git:
            repo: "{{ st_repo }}"
            dest: ~/st/
            clone: yes
          vars:
            st_repo: https://github.com/tuxxy/st

        - name: Build and install st
          become: yes
          shell: 'make clean install'
          args:
            chdir: ~/st/


    - name: Cleanup
      shell: 'rm -rf ~/dotfiles'
